style(shell): apply shfmt (-i 2 -ci -s)

diff --git a/dot_local/bin/executable_doasedit b/dot_local/bin/executable_doasedit
--- a/dot_local/bin/executable_doasedit
+++ b/dot_local/bin/executable_doasedit
@@ -41,15 +41,15 @@ check_doas_conf() {
       printf '(E)dit again, (O)verwrite anyway, (A)bort: [E/o/a]? '
       read -r choice
       case "$choice" in
-      o | O)
-        return 0
-        ;;
-      a | A)
-        return 1
-        ;;
-      e | E | *)
-        "$editor_cmd" "$tmpfile"
-        ;;
+        o | O)
+          return 0
+          ;;
+        a | A)
+          return 1
+          ;;
+        e | E | *)
+          "$editor_cmd" "$tmpfile"
+          ;;
       esac
     done
   fi
@@ -71,26 +71,26 @@ _exit() {
 
 while [ "${#}" -ne 0 ]; do
   case "${1}" in
-  --)
-    shift
-    break
-    ;;
-  --help | -h)
-    help
-    exit 0
-    ;;
-  --version | -V)
-    printf 'doasedit version 1.0.7\n'
-    exit 0
-    ;;
-  -*)
-    printf "doasedit: invalid option: '%s'\n" "${1}"
-    help
-    exit 1
-    ;;
-  *)
-    break
-    ;;
+    --)
+      shift
+      break
+      ;;
+    --help | -h)
+      help
+      exit 0
+      ;;
+    --version | -V)
+      printf 'doasedit version 1.0.7\n'
+      exit 0
+      ;;
+    -*)
+      printf "doasedit: invalid option: '%s'\n" "${1}"
+      help
+      exit 1
+      ;;
+    *)
+      break
+      ;;
   esac
 done
 
